<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Nopackage"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="21.414">
  <properties />
            <testcase name="userManage" time="0.310" classname="tests.AddInquire_Test">
                <failure type="org.testng.internal.reflect.MethodMatcherException"
                  message="
[public void tests.AddInquire_Test.userManage(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: userManage([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) firstname,(java.lang.String) yingying,(java.lang.String) lastname,(java.lang.String) pei,(java.lang.String) token,(java.lang.String) 111.0,(java.lang.String) email,(java.lang.String) 652978478@qq.com,(java.lang.String) emailstatus,(java.lang.String) OK,(java.lang.String) usesleft,(java.lang.String) 1.0]"
              >
<![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void tests.AddInquire_Test.userManage(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: userManage([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) firstname,(java.lang.String) yingying,(java.lang.String) lastname,(java.lang.String) pei,(java.lang.String) token,(java.lang.String) 111.0,(java.lang.String) email,(java.lang.String) 652978478@qq.com,(java.lang.String) emailstatus,(java.lang.String) OK,(java.lang.String) usesleft,(java.lang.String) 1.0]
  org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
  org.testng.internal.Parameters.injectParameters(Parameters.java:909)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.TestNG.privateMain(TestNG.java:1336)
  org.testng.TestNG.main(TestNG.java:1304)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="login" time="21.104" classname="tests.AddInquire_Test" />
      
</testsuite>
